CREATE TABLE BOOKS
(
    ID    INT PRIMARY KEY,
    TITLE VARCHAR(255),
    PRICE NUMERIC
);
CREATE TABLE AUTHORS
(
    ID        INT PRIMARY KEY,
    FIRSTNAME VARCHAR(255),
    LASTNAME  VARCHAR(255)
);
CREATE TABLE BOOKS_AUTHORS
(
    AUTHOR_ID INT NOT NULL,
    BOOK_ID   INT NOT NULL
);
ALTER TABLE BOOKS_AUTHORS
    ADD FOREIGN KEY (AUTHOR_ID)
        REFERENCES AUTHORS (ID);
ALTER TABLE BOOKS_AUTHORS
    ADD FOREIGN KEY (BOOK_ID)
        REFERENCES BOOKS (ID);
CREATE TABLE CART
(
    ID         INT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL REFERENCES books (id)
);