INSERT INTO AUTHORS VALUES (1, 'Heinrich', 'Böll');
INSERT INTO AUTHORS VALUES (2, 'Tennessee', 'Williams');
INSERT INTO BOOKS VALUES (1, 'The Clown');
INSERT INTO BOOKS VALUES (2, 'A Streetcar Named Desire');
INSERT INTO BOOKS_AUTHORS(AUTHOR_ID, BOOK_ID) VALUES (1, 1);
INSERT INTO BOOKS_AUTHORS(AUTHOR_ID, BOOK_ID) VALUES (2, 2);